#!/usr/bin/env python3
"""Train a tiny hashed character n-gram intent classifier without dependencies."""
import argparse
import json
import math
import re
from pathlib import Path

FEATURES = 256
NGRAM_MIN = 2
NGRAM_MAX = 5


def feature_ids(text):
    text = " " + re.sub(r"\s+", " ", text.lower().strip()) + " "
    for n in range(NGRAM_MIN, NGRAM_MAX + 1):
        for i in range(len(text) - n + 1):
            # Stable FNV-1a hash; Python's hash is intentionally randomized.
            h = 2166136261
            for byte in text[i:i+n].encode("utf-8"):
                h = ((h ^ byte) * 16777619) & 0xffffffff
            yield h % FEATURES


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("dataset", type=Path)
    parser.add_argument("--out", type=Path, default=Path("model/intent_model.h"))
    parser.add_argument("--epochs", type=int, default=160)
    parser.add_argument("--learning-rate", type=float, default=0.08)
    args = parser.parse_args()

    rows = [json.loads(line) for line in args.dataset.read_text().splitlines() if line.strip()]
    labels = sorted({row["intent"] for row in rows})
    label_index = {label: i for i, label in enumerate(labels)}
    weights = [[0.0] * FEATURES for _ in labels]
    biases = [0.0] * len(labels)

    for _ in range(args.epochs):
        for row in rows:
            ids = list(feature_ids(row["text"]))
            scores = [biases[c] + sum(weights[c][i] for i in ids) for c in range(len(labels))]
            maximum = max(scores)
            probabilities = [math.exp(score - maximum) for score in scores]
            total = sum(probabilities)
            probabilities = [value / total for value in probabilities]
            target = label_index[row["intent"]]
            for c in range(len(labels)):
                error = probabilities[c] - (1.0 if c == target else 0.0)
                biases[c] -= args.learning_rate * error
                for feature in ids:
                    weights[c][feature] -= args.learning_rate * error

    args.out.parent.mkdir(parents=True, exist_ok=True)
    with args.out.open("w") as output:
        output.write("// Generated by model/train_ngram.py; do not edit.\n#pragma once\n\n")
        output.write(f"#define MICRONEEDLE_MODEL_FEATURES {FEATURES}\n")
        output.write(f"#define MICRONEEDLE_MODEL_CLASSES {len(labels)}\n")
        output.write("static const char *const microneedle_model_labels[] = {\n")
        for label in labels:
            output.write(f'  "{label}",\n')
        output.write("};\n\n")
        output.write("static const float microneedle_model_bias[] = {\n  ")
        output.write(", ".join(f"{value:.8f}f" for value in biases))
        output.write("\n};\n\nstatic const float microneedle_model_weights[] = {\n")
        for row in weights:
            output.write("  " + ", ".join(f"{value:.8f}f" for value in row) + ",\n")
        output.write("};\n")

    print(f"wrote {args.out} ({len(labels)} classes, {FEATURES} hashed features)")


if __name__ == "__main__":
    main()
